### ISSUE TITLE
show all posts on home page

### ISSUE THREAD

**Issue by friedqi** [clente/hugo-bearcub#1]
HI, I'd like to list the blog posts on the home page.  What should I do?  thanks

**Comment by cnnrshd** [comment]
You might've solved this by now, but here's (my) understanding of the process.
The goal is to list all of your blog posts. 
- To do this, you'll need to loop over all posts.
- To loop over all posts, you need to use a [Template](https://gohugo.io/templates/introduction/).
- To use a template, you need to define a [Layout](https://gohugo.io/templates/homepage/#example-homepage-template).

The Layout link should take you directly to a page on Hugo's site where it talks about showing the 10 most recent posts. `bearcub` has some additional page types that don't count as blog posts, and if you start using [Page Bundles](https://gohugo.io/content-management/page-bundles/) then you won't want to show every *Page*, you'll want to show every *RegularPage*.

Below is a layout I just tested that should do what you're looking for, since it works for my blog:

```html
{{ define "main" }}
<!-- This .Content will insert the content from your root _index.md -->
{{ .Content }}

<h2>Posts</h2>
<ul>
<!-- Look through every RegularPage - see here https://gohugo.io/variables/site/#site-variables-list -->
{{ range .Site.RegularPages }}
    <!-- Filter out any "addons" pages - this will remove /admin, /author, /sections -->
    {{ if ne .Params.type "addons" }}
        <!-- This is the HTML for each post -->
        <li>
            <span>
                <i>
                <time datetime='{{ .Date.Format "2006-01-02" }}' pubdate>
                    {{ .Date.Format (default "2006-01-02" .Site.Params.dateFormat) }}
                </time>
                </i>
            </span>
            <a href="{{ .Permalink }}">{{ .Title }}</a>
        </li>
    {{ end }}
{{ end }}
</ul>

{{ end }}
```
Relevant files are:
```txt
content/_index.md
layouts/index.html
```

**Comment by clente** [comment]
Sorry it took me such a long time to get to your issue... For some weird reason I wasn't watching my own repo 😅

Unfortunately your question has more to do with Hugo than with my specific template. You might want to follow @cnnrshd's advice or check out [Hugo's documentation](https://gohugo.io/documentation/).
